### ISSUE TITLE
Add a direct link to the file sub-001_task-rest_run-1_bold.nii.gz

### ISSUE THREAD

**Issue by MarcSkovMadsen** [matteomancini/neurosnippets#1]
Hi Matteo

I am a contributor to Panel (https://awesome-panel.org) and would like to play around with your example. Unfortunately I am not able to install and use the datalad tool due to corporate security restrictions. Would it be possible to provide a direct link to the file?

sub-001_task-rest_run-1_bold.nii.gz

Thanks.

**Comment by matteomancini** [comment]
Hi Marc,
thanks for the interest! As mentioned in the [related post](https://neurosnippets.com/posts/game-of-dashboards/#post), the dataset is hosted on [OpenNeuro](https://openneuro.org/datasets/ds000243/versions/00001). On that page, you should be able to explore the dataset tree and manually download the file. Here is a [direct link](https://openneuro.org/crn/datasets/ds000243/snapshots/00001/files/sub-001:func:sub-001_task-rest_run-1_bold.nii.gz).
